server:
  # WEB端口、服务注册发现端口，Eureka默认端口为8761
  port: 20001

# 当前Spring应用名称，默认为null，相同命名的应用会注册到同一个服务集群中
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-provider-hystrix-payment #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/hystrix/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-provider-hystrix-payment #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/circuit/**         # 断言，路径相匹配的进行路由
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
# Eureka配置
eureka:
  client:
    # 修改注册中心地址，集群时，用逗号分隔多个地址，Eureka默认地址为http://localhost:8761/eureka/
    service-url:
      defaultZone: http://localhost:8761/eureka/