package com.test.bean;

import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

@NoArgsConstructor
@Data
public class DsmsTrainers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.TRAINER_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String trainerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.PASSWORD
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.NAME
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.GENDER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.AGE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.DRIVING_YEARS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Short drivingYears;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.PHONE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.ID_NUMBER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.LICENSE_TYPE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String licenseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.LICENSE_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String licenseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.CAR_ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.SALARY
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.JOIN_DATE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Date joinDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.FLAG
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.COMMENTS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DSMS_TRAINERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
}