package com.test.bean;

import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

@NoArgsConstructor
public class DsmsTrainees implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.TRAINEE_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String traineeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.PASSWORD
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.NAME
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.GENDER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.AGE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.HEIGHT
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Short height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.PHONE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.ADDRESS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.ID_NUMBER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.ENTER_DATE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Date enterDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.APPLICATION_TYPE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String applicationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.STATUS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.TRAINER_ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long trainerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.FLAG
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINEES.COMMENTS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.ID
     *
     * @return the value of DSMS_TRAINEES.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.ID
     *
     * @param id the value for DSMS_TRAINEES.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.TRAINEE_NO
     *
     * @return the value of DSMS_TRAINEES.TRAINEE_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getTraineeNo() {
        return traineeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.TRAINEE_NO
     *
     * @param traineeNo the value for DSMS_TRAINEES.TRAINEE_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setTraineeNo(String traineeNo) {
        this.traineeNo = traineeNo == null ? null : traineeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.PASSWORD
     *
     * @return the value of DSMS_TRAINEES.PASSWORD
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.PASSWORD
     *
     * @param password the value for DSMS_TRAINEES.PASSWORD
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.NAME
     *
     * @return the value of DSMS_TRAINEES.NAME
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.NAME
     *
     * @param name the value for DSMS_TRAINEES.NAME
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.GENDER
     *
     * @return the value of DSMS_TRAINEES.GENDER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.GENDER
     *
     * @param gender the value for DSMS_TRAINEES.GENDER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.AGE
     *
     * @return the value of DSMS_TRAINEES.AGE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.AGE
     *
     * @param age the value for DSMS_TRAINEES.AGE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.HEIGHT
     *
     * @return the value of DSMS_TRAINEES.HEIGHT
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Short getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.HEIGHT
     *
     * @param height the value for DSMS_TRAINEES.HEIGHT
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setHeight(Short height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.PHONE
     *
     * @return the value of DSMS_TRAINEES.PHONE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Long getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.PHONE
     *
     * @param phone the value for DSMS_TRAINEES.PHONE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.ADDRESS
     *
     * @return the value of DSMS_TRAINEES.ADDRESS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.ADDRESS
     *
     * @param address the value for DSMS_TRAINEES.ADDRESS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.ID_NUMBER
     *
     * @return the value of DSMS_TRAINEES.ID_NUMBER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.ID_NUMBER
     *
     * @param idNumber the value for DSMS_TRAINEES.ID_NUMBER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.ENTER_DATE
     *
     * @return the value of DSMS_TRAINEES.ENTER_DATE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Date getEnterDate() {
        return enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.ENTER_DATE
     *
     * @param enterDate the value for DSMS_TRAINEES.ENTER_DATE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setEnterDate(Date enterDate) {
        this.enterDate = enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.APPLICATION_TYPE
     *
     * @return the value of DSMS_TRAINEES.APPLICATION_TYPE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getApplicationType() {
        return applicationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.APPLICATION_TYPE
     *
     * @param applicationType the value for DSMS_TRAINEES.APPLICATION_TYPE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setApplicationType(String applicationType) {
        this.applicationType = applicationType == null ? null : applicationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.STATUS
     *
     * @return the value of DSMS_TRAINEES.STATUS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.STATUS
     *
     * @param status the value for DSMS_TRAINEES.STATUS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.TRAINER_ID
     *
     * @return the value of DSMS_TRAINEES.TRAINER_ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Long getTrainerId() {
        return trainerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.TRAINER_ID
     *
     * @param trainerId the value for DSMS_TRAINEES.TRAINER_ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setTrainerId(Long trainerId) {
        this.trainerId = trainerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.FLAG
     *
     * @return the value of DSMS_TRAINEES.FLAG
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.FLAG
     *
     * @param flag the value for DSMS_TRAINEES.FLAG
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINEES.COMMENTS
     *
     * @return the value of DSMS_TRAINEES.COMMENTS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINEES.COMMENTS
     *
     * @param comments the value for DSMS_TRAINEES.COMMENTS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", traineeNo=").append(traineeNo);
        sb.append(", password=").append(password);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", age=").append(age);
        sb.append(", height=").append(height);
        sb.append(", phone=").append(phone);
        sb.append(", address=").append(address);
        sb.append(", idNumber=").append(idNumber);
        sb.append(", enterDate=").append(enterDate);
        sb.append(", applicationType=").append(applicationType);
        sb.append(", status=").append(status);
        sb.append(", trainerId=").append(trainerId);
        sb.append(", flag=").append(flag);
        sb.append(", comments=").append(comments);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}