package com.test.bean;

import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

@NoArgsConstructor
public class DsmsCars implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_CARS.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_CARS.TRAINER_ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long trainerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_CARS.CAR_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String carNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_CARS.CAR_BRAND
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String carBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_CARS.CAR_TYPE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_CARS.PRICE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_CARS.ENGINE_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String engineNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_CARS.STATUS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_CARS.BUY_DATE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Date buyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_CARS.COMMENTS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DSMS_CARS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_CARS.ID
     *
     * @return the value of DSMS_CARS.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_CARS.ID
     *
     * @param id the value for DSMS_CARS.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_CARS.TRAINER_ID
     *
     * @return the value of DSMS_CARS.TRAINER_ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Long getTrainerId() {
        return trainerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_CARS.TRAINER_ID
     *
     * @param trainerId the value for DSMS_CARS.TRAINER_ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setTrainerId(Long trainerId) {
        this.trainerId = trainerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_CARS.CAR_NO
     *
     * @return the value of DSMS_CARS.CAR_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getCarNo() {
        return carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_CARS.CAR_NO
     *
     * @param carNo the value for DSMS_CARS.CAR_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setCarNo(String carNo) {
        this.carNo = carNo == null ? null : carNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_CARS.CAR_BRAND
     *
     * @return the value of DSMS_CARS.CAR_BRAND
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getCarBrand() {
        return carBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_CARS.CAR_BRAND
     *
     * @param carBrand the value for DSMS_CARS.CAR_BRAND
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setCarBrand(String carBrand) {
        this.carBrand = carBrand == null ? null : carBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_CARS.CAR_TYPE
     *
     * @return the value of DSMS_CARS.CAR_TYPE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_CARS.CAR_TYPE
     *
     * @param carType the value for DSMS_CARS.CAR_TYPE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_CARS.PRICE
     *
     * @return the value of DSMS_CARS.PRICE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_CARS.PRICE
     *
     * @param price the value for DSMS_CARS.PRICE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_CARS.ENGINE_NO
     *
     * @return the value of DSMS_CARS.ENGINE_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getEngineNo() {
        return engineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_CARS.ENGINE_NO
     *
     * @param engineNo the value for DSMS_CARS.ENGINE_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setEngineNo(String engineNo) {
        this.engineNo = engineNo == null ? null : engineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_CARS.STATUS
     *
     * @return the value of DSMS_CARS.STATUS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_CARS.STATUS
     *
     * @param status the value for DSMS_CARS.STATUS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_CARS.BUY_DATE
     *
     * @return the value of DSMS_CARS.BUY_DATE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Date getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_CARS.BUY_DATE
     *
     * @param buyDate the value for DSMS_CARS.BUY_DATE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setBuyDate(Date buyDate) {
        this.buyDate = buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_CARS.COMMENTS
     *
     * @return the value of DSMS_CARS.COMMENTS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_CARS.COMMENTS
     *
     * @param comments the value for DSMS_CARS.COMMENTS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_CARS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", trainerId=").append(trainerId);
        sb.append(", carNo=").append(carNo);
        sb.append(", carBrand=").append(carBrand);
        sb.append(", carType=").append(carType);
        sb.append(", price=").append(price);
        sb.append(", engineNo=").append(engineNo);
        sb.append(", status=").append(status);
        sb.append(", buyDate=").append(buyDate);
        sb.append(", comments=").append(comments);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}