package com.test.mapper;

import com.test.bean.DsmsTrainees;
import com.test.bean.DsmsTraineesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DsmsTraineesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    long countByExample(DsmsTraineesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int deleteByExample(DsmsTraineesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int insert(DsmsTrainees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int insertSelective(DsmsTrainees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    List<DsmsTrainees> selectByExample(DsmsTraineesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    DsmsTrainees selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") DsmsTrainees record, @Param("example") DsmsTraineesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByExample(@Param("record") DsmsTrainees record, @Param("example") DsmsTraineesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByPrimaryKeySelective(DsmsTrainees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINEES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByPrimaryKey(DsmsTrainees record);
}