package com.test.mapper;

import com.test.bean.DsmsFinances;
import com.test.bean.DsmsFinancesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DsmsFinancesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_FINANCES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    long countByExample(DsmsFinancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_FINANCES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int deleteByExample(DsmsFinancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_FINANCES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_FINANCES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int insert(DsmsFinances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_FINANCES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int insertSelective(DsmsFinances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_FINANCES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    List<DsmsFinances> selectByExample(DsmsFinancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_FINANCES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    DsmsFinances selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_FINANCES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") DsmsFinances record, @Param("example") DsmsFinancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_FINANCES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByExample(@Param("record") DsmsFinances record, @Param("example") DsmsFinancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_FINANCES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByPrimaryKeySelective(DsmsFinances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_FINANCES
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByPrimaryKey(DsmsFinances record);
}