# 端口配置
server:
  port: 10086
# 配置数据库连接参数
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: test
    url: jdbc:mysql://localhost:3306/test
# mybatis 配置
mybatis:
  # 加载MyBatis的mapper.xml
  mapper-locations: classpath:mapper/*.xml
  # 设置实体类包别名
  type-aliases-package: com.test.bean
