server:
  port: 8001
spring:
  application:
    name: EurekaServer8001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka2:8002/eureka/
  instance:
    hostname: eureka1