server:
  # WEB端口、服务注册发现端口，Eureka默认端口为8761
  port: 30001

# 当前Spring应用名称，默认为null，相同命名的应用会注册到同一个服务集群中
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zzyybs/springcloud-config.git #GitHub上面的git仓库名字
          username: root
          password: root
          #搜索目录
          search-paths:
            - springcloud-config
      #默认读取分支
      label: master
# Eureka配置
eureka:
  client:
    # 修改注册中心地址，集群时，用逗号分隔多个地址，Eureka默认地址为http://localhost:8761/eureka/
    service-url:
      defaultZone: http://localhost:8761/eureka/