package com.test.bean;

import java.io.Serializable;

public class DsmsAdmins implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_ADMINS.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_ADMINS.USERNAME
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_ADMINS.PASSWORD
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_ADMINS.FLAG
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DSMS_ADMINS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_ADMINS.ID
     *
     * @return the value of DSMS_ADMINS.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_ADMINS.ID
     *
     * @param id the value for DSMS_ADMINS.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_ADMINS.USERNAME
     *
     * @return the value of DSMS_ADMINS.USERNAME
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_ADMINS.USERNAME
     *
     * @param username the value for DSMS_ADMINS.USERNAME
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_ADMINS.PASSWORD
     *
     * @return the value of DSMS_ADMINS.PASSWORD
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_ADMINS.PASSWORD
     *
     * @param password the value for DSMS_ADMINS.PASSWORD
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_ADMINS.FLAG
     *
     * @return the value of DSMS_ADMINS.FLAG
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_ADMINS.FLAG
     *
     * @param flag the value for DSMS_ADMINS.FLAG
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_ADMINS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", flag=").append(flag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}