package com.test.bean;

import java.io.Serializable;
import java.util.Date;

public class DsmsLogs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_LOGS.ID
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
	public DsmsLogs() {}
	public DsmsLogs(Long id, Long itemId, String logEvent, Date logDate, String flag) {
		super();
		this.id = id;
		this.itemId = itemId;
		this.logEvent = logEvent;
		this.logDate = logDate;
		this.flag = flag;
	}
    private Long id;


	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_LOGS.ITEM_ID
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_LOGS.LOG_EVENT
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    private String logEvent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_LOGS.LOG_DATE
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    private Date logDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_LOGS.FLAG
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_LOGS.ID
     *
     * @return the value of DSMS_LOGS.ID
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_LOGS.ID
     *
     * @param id the value for DSMS_LOGS.ID
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_LOGS.ITEM_ID
     *
     * @return the value of DSMS_LOGS.ITEM_ID
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_LOGS.ITEM_ID
     *
     * @param itemId the value for DSMS_LOGS.ITEM_ID
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_LOGS.LOG_EVENT
     *
     * @return the value of DSMS_LOGS.LOG_EVENT
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    public String getLogEvent() {
        return logEvent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_LOGS.LOG_EVENT
     *
     * @param logEvent the value for DSMS_LOGS.LOG_EVENT
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    public void setLogEvent(String logEvent) {
        this.logEvent = logEvent == null ? null : logEvent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_LOGS.LOG_DATE
     *
     * @return the value of DSMS_LOGS.LOG_DATE
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_LOGS.LOG_DATE
     *
     * @param logDate the value for DSMS_LOGS.LOG_DATE
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_LOGS.FLAG
     *
     * @return the value of DSMS_LOGS.FLAG
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_LOGS.FLAG
     *
     * @param flag the value for DSMS_LOGS.FLAG
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", itemId=").append(itemId);
        sb.append(", logEvent=").append(logEvent);
        sb.append(", logDate=").append(logDate);
        sb.append(", flag=").append(flag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}