package com.test.bean;

import java.io.Serializable;
import java.util.Date;

public class DsmsTrainers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.TRAINER_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String trainerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.PASSWORD
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.NAME
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.GENDER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.AGE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.DRIVING_YEARS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Short drivingYears;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.PHONE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.ID_NUMBER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.LICENSE_TYPE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String licenseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.LICENSE_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String licenseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.CAR_ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.SALARY
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Long salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.JOIN_DATE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private Date joinDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.FLAG
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSMS_TRAINERS.COMMENTS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DSMS_TRAINERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.ID
     *
     * @return the value of DSMS_TRAINERS.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.ID
     *
     * @param id the value for DSMS_TRAINERS.ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.TRAINER_NO
     *
     * @return the value of DSMS_TRAINERS.TRAINER_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getTrainerNo() {
        return trainerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.TRAINER_NO
     *
     * @param trainerNo the value for DSMS_TRAINERS.TRAINER_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setTrainerNo(String trainerNo) {
        this.trainerNo = trainerNo == null ? null : trainerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.PASSWORD
     *
     * @return the value of DSMS_TRAINERS.PASSWORD
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.PASSWORD
     *
     * @param password the value for DSMS_TRAINERS.PASSWORD
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.NAME
     *
     * @return the value of DSMS_TRAINERS.NAME
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.NAME
     *
     * @param name the value for DSMS_TRAINERS.NAME
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.GENDER
     *
     * @return the value of DSMS_TRAINERS.GENDER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.GENDER
     *
     * @param gender the value for DSMS_TRAINERS.GENDER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.AGE
     *
     * @return the value of DSMS_TRAINERS.AGE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.AGE
     *
     * @param age the value for DSMS_TRAINERS.AGE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.DRIVING_YEARS
     *
     * @return the value of DSMS_TRAINERS.DRIVING_YEARS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Short getDrivingYears() {
        return drivingYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.DRIVING_YEARS
     *
     * @param drivingYears the value for DSMS_TRAINERS.DRIVING_YEARS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setDrivingYears(Short drivingYears) {
        this.drivingYears = drivingYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.PHONE
     *
     * @return the value of DSMS_TRAINERS.PHONE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Long getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.PHONE
     *
     * @param phone the value for DSMS_TRAINERS.PHONE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.ID_NUMBER
     *
     * @return the value of DSMS_TRAINERS.ID_NUMBER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.ID_NUMBER
     *
     * @param idNumber the value for DSMS_TRAINERS.ID_NUMBER
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.LICENSE_TYPE
     *
     * @return the value of DSMS_TRAINERS.LICENSE_TYPE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getLicenseType() {
        return licenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.LICENSE_TYPE
     *
     * @param licenseType the value for DSMS_TRAINERS.LICENSE_TYPE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setLicenseType(String licenseType) {
        this.licenseType = licenseType == null ? null : licenseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.LICENSE_NO
     *
     * @return the value of DSMS_TRAINERS.LICENSE_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.LICENSE_NO
     *
     * @param licenseNo the value for DSMS_TRAINERS.LICENSE_NO
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo == null ? null : licenseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.CAR_ID
     *
     * @return the value of DSMS_TRAINERS.CAR_ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Long getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.CAR_ID
     *
     * @param carId the value for DSMS_TRAINERS.CAR_ID
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setCarId(Long carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.SALARY
     *
     * @return the value of DSMS_TRAINERS.SALARY
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Long getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.SALARY
     *
     * @param salary the value for DSMS_TRAINERS.SALARY
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setSalary(Long salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.JOIN_DATE
     *
     * @return the value of DSMS_TRAINERS.JOIN_DATE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.JOIN_DATE
     *
     * @param joinDate the value for DSMS_TRAINERS.JOIN_DATE
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.FLAG
     *
     * @return the value of DSMS_TRAINERS.FLAG
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.FLAG
     *
     * @param flag the value for DSMS_TRAINERS.FLAG
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSMS_TRAINERS.COMMENTS
     *
     * @return the value of DSMS_TRAINERS.COMMENTS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSMS_TRAINERS.COMMENTS
     *
     * @param comments the value for DSMS_TRAINERS.COMMENTS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_TRAINERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", trainerNo=").append(trainerNo);
        sb.append(", password=").append(password);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", age=").append(age);
        sb.append(", drivingYears=").append(drivingYears);
        sb.append(", phone=").append(phone);
        sb.append(", idNumber=").append(idNumber);
        sb.append(", licenseType=").append(licenseType);
        sb.append(", licenseNo=").append(licenseNo);
        sb.append(", carId=").append(carId);
        sb.append(", salary=").append(salary);
        sb.append(", joinDate=").append(joinDate);
        sb.append(", flag=").append(flag);
        sb.append(", comments=").append(comments);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}