package com.test.mapper;

import com.test.bean.DsmsLogs;
import com.test.bean.DsmsLogsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DsmsLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    long countByExample(DsmsLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    int deleteByExample(DsmsLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    int insert(DsmsLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    int insertSelective(DsmsLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    List<DsmsLogs> selectByExample(DsmsLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    DsmsLogs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") DsmsLogs record, @Param("example") DsmsLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    int updateByExample(@Param("record") DsmsLogs record, @Param("example") DsmsLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    int updateByPrimaryKeySelective(DsmsLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_LOGS
     *
     * @mbg.generated Thu May 23 23:24:09 CST 2019
     */
    int updateByPrimaryKey(DsmsLogs record);
}