package com.test.mapper;

import com.test.bean.DsmsExamOrders;
import com.test.bean.DsmsExamOrdersExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DsmsExamOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_EXAM_ORDERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    long countByExample(DsmsExamOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_EXAM_ORDERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int deleteByExample(DsmsExamOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_EXAM_ORDERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_EXAM_ORDERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int insert(DsmsExamOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_EXAM_ORDERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int insertSelective(DsmsExamOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_EXAM_ORDERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    List<DsmsExamOrders> selectByExample(DsmsExamOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_EXAM_ORDERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    DsmsExamOrders selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_EXAM_ORDERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") DsmsExamOrders record, @Param("example") DsmsExamOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_EXAM_ORDERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByExample(@Param("record") DsmsExamOrders record, @Param("example") DsmsExamOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_EXAM_ORDERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByPrimaryKeySelective(DsmsExamOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSMS_EXAM_ORDERS
     *
     * @mbg.generated Fri May 17 00:30:56 CST 2019
     */
    int updateByPrimaryKey(DsmsExamOrders record);
}